[project]
name = "pippin"
version = "0.1.0"
description = "A CLI for iOS Automation"
readme = "README.md"
requires-python = ">=3.9"
dependencies = []

[project.scripts]
pippin = "pippin.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
